import { StyleSheet } from 'react-native';
import type { AppColors } from '../theme/palette';

export function createAuthLayoutStyles(colors: AppColors) {
  return StyleSheet.create({
    safe: { flex: 1, backgroundColor: colors.background },
    scrollContent: {
      flexGrow: 1,
      paddingHorizontal: 24,
      paddingTop: 18,
      paddingBottom: 40,
    },
    headerRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 8,
      minHeight: 44,
    },
    backBtn: {
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: colors.mutedBg,
      alignItems: 'center',
      justifyContent: 'center',
    },
    hero: {
      alignItems: 'center',
      marginBottom: 28,
    },
    badge: {
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 20,
      backgroundColor: colors.mutedBg,
      marginBottom: 12,
    },
    badgeText: {
      fontSize: 12,
      fontWeight: '700',
      letterSpacing: 0.6,
      color: colors.primary,
      textTransform: 'uppercase',
    },
    title: {
      fontSize: 26,
      fontWeight: '800',
      color: colors.text,
      textAlign: 'center',
      letterSpacing: -0.3,
    },
    subtitle: {
      marginTop: 10,
      fontSize: 15,
      lineHeight: 22,
      color: colors.subtext,
      textAlign: 'center',
      paddingHorizontal: 8,
    },
    inputWrap: {
      flexDirection: 'row',
      alignItems: 'center',
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 14,
      paddingHorizontal: 14,
      marginBottom: 14,
      backgroundColor: colors.mutedBg,
      minHeight: 52,
    },
    inputWrapFocused: {
      borderColor: colors.primary,
      backgroundColor: colors.background,
    },
    input: {
      flex: 1,
      fontSize: 16,
      color: colors.text,
      paddingVertical: 12,
    },
    primaryBtn: {
      marginTop: 8,
      paddingVertical: 16,
      borderRadius: 14,
      backgroundColor: colors.primary,
      alignItems: 'center',
      justifyContent: 'center',
      shadowColor: colors.primary,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.25,
      shadowRadius: 8,
      elevation: 4,
    },
    primaryBtnDisabled: { opacity: 0.65 },
    primaryBtnText: { color: colors.onPrimary, fontSize: 16, fontWeight: '700' },
    outlineBtn: {
      marginTop: 12,
      paddingVertical: 14,
      borderRadius: 14,
      borderWidth: 2,
      borderColor: colors.primary,
      alignItems: 'center',
    },
    outlineBtnText: { color: colors.primary, fontSize: 16, fontWeight: '700' },
    footerNote: {
      marginTop: 24,
      fontSize: 13,
      lineHeight: 19,
      color: colors.subtext,
      textAlign: 'center',
    },
    linkRow: { marginTop: 20, alignItems: 'center' },
    linkMuted: { fontSize: 14, color: colors.subtext },
    linkAccent: { fontSize: 15, fontWeight: '700', color: colors.primary, marginTop: 6 },
    successCard: {
      marginTop: 20,
      padding: 16,
      borderRadius: 14,
      backgroundColor: colors.mutedBg,
      borderWidth: 1,
      borderColor: colors.border,
    },
    successTitle: { fontSize: 15, fontWeight: '700', color: colors.text, marginBottom: 6 },
    successText: { fontSize: 14, lineHeight: 20, color: colors.subtext },
  });
}
